sudo: required
services:
  - docker

before_install:
  - docker build -t hamedsahebi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hamedsahebi/react-test npm test -- --coverage

after_success:
  - docker build -t 1740021886/multi-client ./client
  - docker build -t 1740021886/multi-nginx ./nginx
  - docker build -t 1740021886/multi-server ./server
  - docker build -t 1740021886/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images into docker hub.
  - docker push 1740021886/multi-client
  - docker push 1740021886/multi-nginx
  - docker push 1740021886/multi-server
  - docker push 1740021886/multi-worker
